### ISSUE TITLE
Template for a dict with variable keys

### ISSUE THREAD

**Issue by palto42** [beetbox/confuse#123]
I'm struggling to define the correct template for a data structure like this:

```yaml
topic:
  first:
    name: FirstName
    address: SomeAddress
  second:
    name: Other Name
    address: SomeWhere
  random_topic:
    name: Surprise
    address: Secret Address
```

The topic keys 'first', 'second' and 'random_topic' in the example should be user defined strings and not fixed by the template.

The goal is to access the validated config like `valid.topic["first"]["name"]`.
