### ISSUE TITLE
Distinct values for development, testing, and production environments

### ISSUE THREAD

**Issue by GitHunter0** [beetbox/confuse#154]
First congratulations for this module, it's very thoughtful.

Can it behave like [RStudio/config](https://github.com/rstudio/config), i.e., get distinct values for development, testing, and production environments?

For example, consider this config.yml:
```
default:
  dataset: "sample_data.csv"
  
production:
  dataset: "complete_data.csv"
```
If I set the environment variable `R_CONFIG_ACTIVE = ""` or `= "default"`, then `config::get("dataset")` would return `sample_data.csv`.
If I set `R_CONFIG_ACTIVE = "production"`, then `config::get("dataset")` would return `complete_data.csv`.

Can `confuse` mimic this useful behavior or provide a simple workaround to achieve that? 

Thank you

**Comment by sampsyo** [comment]
That's an interesting feature! I think it's pretty common to accomplish this using Confuse one of two ways, both of which involve separate files instead of having everything within one file:

* Using the environment variable that controls where to look for the configuration, i.e., `APPNAMEDIR` (see the docs).
* Overlaying a second config file. Beets does this with `beet -c <file>`, for example: https://beets.readthedocs.io/en/stable/reference/cli.html#global-flags

Another way you could do it, however, would work like that R package: you could just use `config['default']` or `config['production']` as the root for everything you look up. For example:

```py
if PROD:
    conf = config['production']
else:
    conf = config['default']
print(conf['dataset'].get(str))
```

I hope this makes sense!

**Comment by GitHunter0** [comment]
@sampsyo , thank you my friend, I took the suggestion of your second approach to come up with a solution using `doetenv`, something like this:
```
dotenv.load_dotenv(".env", override=True, verbose=True) # load environment variable 'ENV_MODE' (default, production, ...)
config = confuse.Configuration('app', read=False)
config.set_file('config.yaml')
config.get()
conf = config.get()[os.getenv("ENV_MODE")]
```
Lastly, is it possible to mimic the `inherits` feature of `RStudio/config`? In the case below, it means that `param1` and `param2` will also be available in `production` with the values set in `default`.
```
default:
  param1: "value1"
  param2: "value2"
  dataset: "sample_data.csv"
  
production:
  inherits: default
  dataset: "complete_data.csv"
```

**Comment by jackwilsdon** [comment]
The easiest way to achieve that kind of inheritance is just by adding the inherited view as another source of the view that is inheriting it:

```Python
import confuse

config = confuse.Configuration("example")
config.set({
    "default": {
        "param1": "value1",
        "param2": "value2",
        "dataset": "sample_data.csv",
    },
    "production": {
        "inherits": "default",
        "dataset": "complete_data.csv",
    }
})

view = config["production"]
# Add the view we inherit from as another source.
view.add(config[view["inherits"].get()])

print(view["param1"].get()) # value1
print(view["dataset"].get()) # complete_data.csv
```

**Comment by GitHunter0** [comment]
Thanks a lot @jackwilsdon , I discovered a simple way to replicate the inheritance feature using `anchors`. See what you think, at least for my purposes it fitted perfectly: 
```
default: &default
  param1: "default"
  param2: "this parameter will be available in 'test' too"

production:
  <<: *default
  param1: "prod"
```
