### ISSUE TITLE
Feature Request: Switch to using sayanarijit/expandvars for as_str_expanded()

### ISSUE THREAD

**Issue by ravensorb** [beetbox/confuse#157]
Was curious if there was any interest in switching over to using https://github.com/sayanarijit/expandvars as it provides support for standard unix/go env variable expansion (can be helpful in setting default values).  

Example of a config file with this syntax:
```
database:
   server: ${DATABASE_SERVER:-localhost}
   port: ${DATABASE_PORT:-5432}
   user: ${DATABASE_USERNAME:-app}
   passsword: ${DATABASE_PASSWORD}
```
