### ISSUE TITLE
list of dicts

### ISSUE THREAD

**Issue by lunne** [beetbox/confuse#41]
hi,
I have not found a way to have a list of dicts and validate it.

this is the config
```
cars:
  - manufacturer: volvo
    color: red
    modell: typec
  - manufacturer: toyota
    color: blue
    modell: typeb
  - manufacturer: volvo
    color: green
    modell: typea

```
example of not working validation:
```

cars: [
    {
      "manufacturer": confuse.String(default=""),
      "color": confuse.String(default=""),
      "modell": confuse.String(default="")
    }
  ]
}
```

in the end i just validated it by:
`cars: list`

but when i run config.dump() i get back the config in yaml but the list as an json/dict
```
something: value
something2: value
cars:  [{"manufacturer":"volvo","color":"red","modell":"typec"},{"manufacturer":"toyota","color":"blue","modell":"typeb"},{"manufacturer":"volvo","color":"green","modell":"typea"}]

```
