### ISSUE TITLE
Compositional config?

### ISSUE THREAD

**Issue by EdwardJB** [beetbox/confuse#56]
I've read the docs but don't think composition is possible. Say I want to define paths in terms of a previous path, `base_dir`.

```yaml
base_dir: /opt/my_app
data_dir: $base_dir/data
```

Will `confuse` expand previously-defined variables?

I realise I can affect this sort of behaviour at the YAML level, with anchors - but since the YAML spec doesn't do concatenation I'd have to define paths as the lists of their segments and recombine them in Python, which isn't ideal:

```yaml
base_dir: &base_dir /opt/my_app
data_dir:
  - *base_dir
  - /data
```

Any suggestions?
