### ISSUE TITLE
Cretae config from template

### ISSUE THREAD

**Issue by palto42** [beetbox/confuse#86]
Is there a way to create a yaml config file from a defined template dict like the one in `/eample/__init__.py`

The use case is to generate a new config file to start with if there is no configuration file defined yet.

config.dump() only dumps the currently loaded config, but I can't find an option how to dump a template dict.

**Comment by sampsyo** [comment]
Hello! What would a "template dict" look like? Would all the values be missing? I'm not 100% clear on how this would work.

**Comment by palto42** [comment]
The file generated would have the default values if defined in the template dict or empty values , if possible the expected type as comment.

From this example template dict:

```
template = {
    'library': confuse.Filename(default='/some/file.name'),
    'import_write': confuse.OneOf([bool, 'ask', 'skip'], default=False),
    'ignore': confuse.StrSeq(),
    'plugins': list,

    'paths': {
        'directory': confuse.Filename(),
        'default': confuse.Filename(relative_to='directory'),
    },

    'servers': confuse.Sequence(
        {
            'hostname': confuse.String(default="localhost",
            'options': confuse.StrSeq(),
        }
    )
```

This should create a file like:

```yaml
library: /some/file.name # Filename
import_write: False # OneOf([bool, 'ask', 'skip'])
ignore: # StrSeq
plugins: # list

paths:
    directory: # Filename
    default: # Filename(relative_to='directory')

servers:
    - hostname: localhost # str
      options: # strSeq
```
