### ISSUE TITLE
Ansible-style variable interpolation

### ISSUE THREAD

**Issue by beasteers** [beetbox/confuse#89]
So this is a thought I've been having for a while, but I wanted to get it on paper. I realize that it's not trivial and I understand if there is resistance to the thought.

In ansible, you can use jinja2 templating to substitute variables into your config. Those variables could be overwritten either by another config or via command line.

Here's my thought:

On the python side:
```python
config = confuse.Config() # no interpolation - same as now
config = confuse.Config(vars_from='vars') # use any vars relative to `vars` key
config = confuse.Config(vars_from='.') # use vars relative to root
config.set({'model_version': v4})
```
Now in the config you can do:
```yaml
vars:
  model_version: v3
# or just (w/ vars_from='.')
model_version: v3

model:
  path: /path/to/model_{{ model_version }}.tf
  output: /output/path/embedding_{{ model_version }}.csv

upload:
  upload_file: '{{ model.output }}'
```

(In order to mimic ansible, the jinja would need to be evaluated when resolving the key, not when loading the config file, btw)
